version: '3.8'

services:
  postgres:
    container_name: nest-forum-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=258794613
      - POSTGRES_DB=forum-nest
      - PGDATA=/data/postgres
    volumes:
      - pgdata:/data/postgres

volumes:
    pgdata:
        driver: local